# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - wordleagiles

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '11.0.13'

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 6.0.202

      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
        
      - name: Install dependencies
        run: dotnet restore

      - name: Publish to folder
        run: msbuild .\MVC\MVC.csproj /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ASP-app
          path: '/published/**'

      - name: Unit tests
        run: |
            dotnet tool install --global dotnet-sonarscanner;

            dotnet tool install --global dotnet-coverage;
                
            dotnet sonarscanner begin /d:sonar.host.url="https://sonarcloud.io" /o:"ninotell" /k:"ninotell_TPAgiles" /d:sonar.login="b758f9ec0969c33bd004383e176eb4b13fa1bc03" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml;

            msbuild AhorcadoTests\WordleTests.csproj;
      
            dotnet-coverage collect 'dotnet test "AhorcadoTests\bin\Debug\WordleTests.dll"' -f xml  -o 'coverage.xml';

            dotnet sonarscanner end /d:sonar.login="b758f9ec0969c33bd004383e176eb4b13fa1bc03";
                
      - name: Run UITests
        run: dotnet test UITests/UITests.csproj --no-restore --verbosity normal
    
    
  deploy:
    runs-on: windows-latest
    needs: [build-and-test]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ASP-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'wordleagiles'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_320A49BC6F974717827E0F218BAFDFE1 }}
          package: .
